services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    
  Loss\Glcrossword\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Loss\Glcrossword\Middleware\GlcrosswordMiddleware:
    public: true
      